### PR TITLE
updated to allow folder and file excludes

### PR DESCRIPTION
**Pull request by rathboma**
So I've added the ability to specify project file and folder exclude patterns.

Not sure if I've done it in the best way, but it works great!

Let me know if you have any proposed changes.

Matthew

### CODE REVIEW

**Comment by orrsella** [comment]
Thanks for the pull request. Sorry for the late response, just got back from vacation. I'll try to take a look at it this week, and merge/release.

Thanks again.

**Comment by orrsella** [comment]
After merging I refactored the plugin a little bit to use sbt `AutoPlugin` which makes it easier to edit settings in `build.sbt` files (requires sbt 0.13.5+). I'll try to release a new version in the next couple of days.

Thanks

**Comment by rathboma** [comment]
Thanks for the merge. Fair enough. I don't really know anything about AutoPlugin, so thanks for the refactor!

Let me know when you push out a new release so i can bump our installed version :-)

Matthew

**Comment by orrsella** [comment]
New version is released. I bumped the version to `1.1.0` because it now requires sbt `0.13.5+` and is an `AutoPlugin`. Please give it a try and let me know if you have any problems.

**Pull request merged**
